---
title: 'Chapter 6 Part 1: Questions'
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---


```{r include=FALSE}
library(knitr)
```


## Book Problem 6.5: Soft Drinks

The fill volume of soft-drink beverage bottles is an important quality characteristic. The volume is measured (approximately) by placing a gauge over the crown and comparing the height of the liquid in the neck of the bottle against a coded scale. On this scale, a reading of zero corresponds to the correct fill height. Fifteen samples of size n = 10 have been analyzed, and the fill heights are shown in Table 6E.5.  
  
  
a. Set up x and s control charts on this process.
Does the process exhibit statistical control?  
b. Set up an R chart, and compare with the s chart
in part (a)  
c. Remove the last observations in each of the last 5 samples and set up x and s control charts on this process

## Book Problem 6.9: Piston Ring  

  
Consider the piston ring data shown in Table 6.3. Set up x and R control charts on this process. Is the process in statistical control?
  
## Book Problem 6.10: Piston Ring Cont
  
Table 6E.7 shows 15 additional samples for the piston ring process (Table 6.3), taken after the initial control charts were established. Plot these data on the x and R chart developed in Exercise 6.9. Is the process in control?  
  
  
  
## Book Problem 6.56: Polymer Viscosity

Continuation of Exercise 6.55. The next five measurements on viscosity are 3163, 3199, 3054, 3147, and 3156. Do these measurements indicate that the process is in statistical control?



